import NavBar from "../components/NavBar"

export const metadata = {
  title: 'Ecommerce Project',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
